# ========================================================
# MIRMIS NIRMIR data processing pipeline 
# Example configuration file example
# 
# Usage:
# mirmis run --config configs/pipeline.example.yaml
#
# Copy this file to e.g.:
#   configs/my_run.yaml
# and edit the paths and settings as needed.
# For detailed descriptions of the fields check README.md
# ========================================================


# --------------------------------------------------------
# Run-time settings
# The paths can be absolute or relative to project root.
# --------------------------------------------------------
run:

  # Path to input data.
  input_dir: "data/ASPECT_data/NIR"

  # Root output directory for generated products
  output_dir: ""

  # SPICE meta kernel path
  spice_dir: ""

  # Overwrite existing outputs if they already exists
  overwrite: true


# --------------------------------------------------------
# Metadata settings
# --------------------------------------------------------
data:

  # Camera ID
  instrume: "NIRMIR"

  # Mission
  origin: "ESA-COMET-INTERCEPTOR"

  # Software identification
  swcreate: "NIRMIRCAL"

  # Mission phase ID
  missphas: "000_test"

  # Mission observation ID
  observ: "pipeline-testing"

  # Observed target
  object: "test"

  # Observed target (SPICE)
  target: "test"


# --------------------------------------------------------
# Pipeline settings
# --------------------------------------------------------
pipeline:

  # Ordered list of pipeline levels to execute.
  # Values: "0", "1", "2", "3"
  levels: ["0"]

  # list of channels included in processin
  # Values: "nir", "mir"
  channels: ["nir", "mir"]

