# ========================================================
# MIRMIS NIRMIR data processing pipeline 
# Example configuration file example
# 
# Usage:
# mirmis run --config configs/pipeline.example.yaml
#
# Copy this file to e.g.:
#   configs/pipeline.yaml
# and edit the paths and settings as needed.
# For detailed descriptions of the fields check README.md
# ========================================================


# --------------------------------------------------------
# Run-time settings
# The paths can be absolute or relative to project root.
# --------------------------------------------------------
run:

  # (Required) Path to input data. Relative to this config file or absolute.
  input_dir: "../data/ASPECT_data/NIR"

  # (Optional) Root output directory for generated products. Relative to this config file or absolute. If left empty outputs folder is used from the repo.
  output_dir: ""

  # (Optional) SPICE meta kernel path. Should be absolute. Optional only from the pipeline perspective
  spice_dir: ""

  # Overwrite existing outputs if they already exists
  overwrite: true


# --------------------------------------------------------
# Metadata settings
# All these fields are required for the pipeline to work
# --------------------------------------------------------
data:

  # Camera ID
  instrume: "NIRMIR"

  # Mission
  origin: "ESA-COMET-INTERCEPTOR"

  # Software identification
  swcreate: "NIRMIRCAL"

  # Mission phase ID
  missphas: "000_test"

  # Mission observation ID
  observ: "pipeline-testing"

  # Observed target
  object: "test"

  # Observed target (SPICE)
  target: "TEST"


# --------------------------------------------------------
# Pipeline settings
# All these fields are required for the pipeline to work
# --------------------------------------------------------
pipeline:

  # List of pipeline levels to execute.
  # Values: "0", "1", "2", "3"
  # E.g. ["0","1"]
  levels: ["0", "1"]

  # List of channels included in processin
  # Values: "NIR", "MIR"
  # E.g. ["NIR"]
  channels: ["NIR"]

