# ========================================================
# MIRMIS NIRMIR data processing pipeline 
# Example configuration file example
# 
# Usage:
# mirmis run --config configs/pipeline.example.yaml
#
# Copy this file to e.g.:
#   configs/pipeline.yaml
# and edit the paths and settings as needed.
# For detailed descriptions of the fields check README.md
# ========================================================


# --------------------------------------------------------
# Run-time settings
# 
# --------------------------------------------------------
run:

  # (Required) Path to input data. Relative to this config file or absolute.
  input_dir: "../data/ASPECT_data/NIR"

  # (Optional) Root output directory for generated products. Absolute or empty. If left empty outputs folder is created to where the pipeline is run.
  output_dir: ""

  # (Optional) SPICE meta kernel path. Should be absolute. Optional only from the pipeline perspective.
  spice_dir: ""

  # Overwrite existing outputs if they already exists
  overwrite: true

# --------------------------------------------------------
# Calibration settings
#   all calibration related files should be inside calibration_dir.
#   Define the relative paths to specific files inside the calibration dir.
#   
# --------------------------------------------------------
calibration: 

  # (Required for level 1) Path to directory containing calibration files. Relative to this config file or absolute.
  calibration_dir: "../calibration"

  # Dark background for NIR channel. relative inside calibration_dir. Used as calibrarion_dir / dark
  # Dark should be fits file with the frame is in the PrimaryHDU
  dark: "DARKS/NIR_DARK.fits"

  # Flat field for NIR channel.
  # Flat should be fits file with the frame is in the PrimaryHDU
  flat: "FLATS/NIR_FLAT.fits"

  # Bad pixel list as a txt file.
  badpixels: "BADPIXELS/NIR_BADPIXELS.txt"

  # Radiance conversion data
  # Radiance files should be txt files
  nir_radiance: "RADIANCE/NIR_RADIANCE.txt"
  mir_radiance: "RADIANCE/MIR_RADIANCE.txt"

  # Solar spectral irradiance
  # Should be csv file
  solar_ssi: "SOLAR/ssi_yearly_avg_e2024_c20250221.csv"


# --------------------------------------------------------
# Metadata settings
# All these fields are required for the pipeline to work
# --------------------------------------------------------
data:

  # Camera ID
  instrume: "NIRMIR"

  # Mission
  origin: "ESA-COMET-INTERCEPTOR"

  # Software identification
  swcreate: "NIRMIRCAL"

  # Mission phase ID
  missphas: "000_test"

  # Mission observation ID
  observ: "pipeline-testing"

  # Observed target
  object: "test"

  # Observed target (SPICE)
  target: "TEST"

  # Solar distance
  # Manually set the solar distance, used in reflectance calibration.
  # Warning setting this value will override the solar distance from SPICE kernel
  # usage: solar disrtance in AU E.G. "1" or "1.2" | "" or None if not used.
  solar_d: ""


# --------------------------------------------------------
# Pipeline settings
# All these fields are required for the pipeline to work
# --------------------------------------------------------
pipeline:

  # List of pipeline levels to execute.
  # Values: "0", "1", "1A", "1A-extra", "1B", "1C"
  # E.g. ["0","1"]
  levels: ["0", "1A", "1A-extra"]

  # List of channels included in processin
  # Values: "NIR", "MIR"
  # E.g. ["NIR"]
  channels: ["NIR"]
